# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GE encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/en/latest/how_to_guides/configuring_data_contexts/how_to_use_a_yaml_file_or_environment_variables_to_populate_credentials.html

instance_id: 9a5bf883-42c2-49c3-9128-a707efea14d3
redshift:
  drivername: postgresql+psycopg2
  host: HOST_PLACEHOLDER
  port: '0000'
  username: USERNAME_PLACEHOLDER
  password: ${REDSHIFT_PASSWORD}
  database: DATABASE_PLACEHOLDER
  query:
    sslmode: prefer
snowflake:
  drivername: snowflake
  username: USERNAME_PLACEHOLDER
  password: ${SNOWFLAKE_PASSWORD}
  host: HOST_PLACEHOLDER
  database: DATABASE_PLACEHOLDER
  query:
    schema: SCHEMA_PLACEHOLDER
    warehouse: WAREHOUSE_PLACEHOLDER
bigquery:
  url: bigquery:///DATASET_PLACEHOLDER?credentials_path=${GOOGLE_APPLICATION_CREDENTIALS}
